apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: foodrecipe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: montassarr/foodrecipe-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: CONNECTION_STRING
              value: "mongodb://mongo:27017/foodRecipe"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: foodrecipe-secrets
                  key: SECRET_KEY
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: foodrecipe-secrets
                  key: STRIPE_SECRET_KEY