
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install && chmod -R 777 /app/node_modules/.bin

COPY . .

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

RUN rm -rf node_modules && npm install && npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

RUN echo 'server { \
    listen 80; \
    location / { \
        root /usr/share/nginx/html; \
        index index.html; \
        try_files $uri $uri/ /index.html; \
    } \
}' > /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]