version: '3.8'

services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - foodrecipe-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - CONNECTION_STRING=mongodb://mongo:27017/foodRecipe
      - SECRET_KEY=KIRTI12345
      - STRIPE_SECRET_KEY=sk_test_VOTRE_NOUVELLE_CLE
      - STRIPE_WEBHOOK_SECRET=whsec_VOTRE_NOUVEAU_WEBHOOK
    depends_on:
      - mongo
    networks:
      - foodrecipe-network

  frontend:
    build: ./frontend/food-blog-app
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - foodrecipe-network

volumes:
  mongo-data:

networks:
  foodrecipe-network:
    driver: bridge